package examples.jtable;

import java.util.Collections;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import osjava.tl3.logic.planning.InputFileHelper;
import osjava.tl3.logic.planning.Scheduler;
import osjava.tl3.logic.planning.strategies.StrategyType;
import osjava.tl3.logic.planning.strategies.helpers.StrategyProtocol;
import osjava.tl3.model.Academic;
import osjava.tl3.model.MasterSchedule;
import osjava.tl3.model.Room;
import osjava.tl3.model.RoomType;
import osjava.tl3.model.Schedule;
import osjava.tl3.model.Semester;
import osjava.tl3.model.StudyProgram;
import osjava.tl3.model.controller.DataController;

/**
 *
 * @author Meikel Bode
 */
public class ScheduleGUI extends javax.swing.JFrame {

    DataController dataController;
    Scheduler scheduler;
    MasterSchedule masterSchedule;

    ScheduleTable scheduleTable;
    ScheduleTableModel scheduleTableModel;

    JLabel lSelectNode;
    
    /**
     * Creates new form ScheduleGUI
     */
    public ScheduleGUI() {
        initComponents();
        init();
        
        setSize(1200, 800);
        setLocationRelativeTo(null);
        
        
    }

    private void init() {

        dataController = new DataController();
        InputFileHelper.loadCourses(dataController);
        InputFileHelper.loadRooms(dataController);
        InputFileHelper.loadStudyPrograms(dataController);

        scheduler = new Scheduler();
        scheduler.setDataController(dataController);
        scheduler.setStrategyType(StrategyType.COST_OPTIMIZED);
        scheduler.executeStrategy(null);

        masterSchedule = scheduler.getMasterSchedule();
        
        initMasterScheduleInfos(masterSchedule);
        
        DefaultTreeModel treeModel = new DefaultTreeModel(buildTreeModel());
        jt.setModel(treeModel);

        scheduleTable = new ScheduleTable();
        scheduleTableModel = new ScheduleTableModel();
        scheduleTable.setModel(scheduleTableModel);

        lSelectNode = new JLabel("Bitte wählen Sie das Objekt in der Baumansicht, dessen Plan Sie einsehen möchten.", SwingConstants.CENTER);
        
        spTable.setViewportView(lSelectNode);
        
    }

    private TreeNode buildTreeModel() {
        DefaultMutableTreeNode rMasterSchedule = new DefaultMutableTreeNode("Gesamtplan");
        DefaultMutableTreeNode rRooms = new DefaultMutableTreeNode("Raumpläne");
        rMasterSchedule.add(rRooms);
        DefaultMutableTreeNode rRoomsInternal = new DefaultMutableTreeNode("Interne Räume");
        List<Room> rooms = masterSchedule.getRooms(RoomType.INTERNAL);
        Collections.sort(rooms);
        for (Room room : rooms) {
            rRoomsInternal.add(new DefaultMutableTreeNode(room));
        }
        rRooms.add(rRoomsInternal);
        
        DefaultMutableTreeNode rRoomsExternal = new DefaultMutableTreeNode("Externe Räume");
        rooms = masterSchedule.getRooms(RoomType.EXTERNAL);
        Collections.sort(rooms);
        for (Room room : rooms) {
            rRoomsExternal.add(new DefaultMutableTreeNode(room));
        }
        rRooms.add(rRoomsExternal);
       

        DefaultMutableTreeNode rAcademics = new DefaultMutableTreeNode("Dozentenpläne");
        List<Academic> academics = dataController.getAcademics();
        Collections.sort(academics);
        for (Academic academic : academics) {
            rAcademics.add(new DefaultMutableTreeNode(academic));
        }
        rMasterSchedule.add(rAcademics);

        DefaultMutableTreeNode rStudyPrograms = new DefaultMutableTreeNode("Studiengangspläne");
        List<StudyProgram> studyPrograms = dataController.getStudyPrograms();
        Collections.sort(studyPrograms);
        for (StudyProgram studyProgram : studyPrograms) {
            DefaultMutableTreeNode rStudyProgram = new DefaultMutableTreeNode(studyProgram);
            rStudyPrograms.add(rStudyProgram);
            for (Semester semester : studyProgram.getSemesters()) {
                rStudyProgram.add(new DefaultMutableTreeNode(semester));
            }
        }
        rMasterSchedule.add(rStudyPrograms);

        return rMasterSchedule;
    }

    
    private void initMasterScheduleInfos(MasterSchedule masterSchedule) {
        lRoomsInternal.setText(String.valueOf(masterSchedule.getRoomCount(RoomType.INTERNAL)));
        lRoomsExternal.setText(String.valueOf(masterSchedule.getRoomCount(RoomType.EXTERNAL)));
        lSeatsExternal.setText(String.valueOf(masterSchedule.getExternalScheduledSeats()));
        lBlocksCount.setText(String.valueOf(masterSchedule.getTotalBlocks(RoomType.INTERNAL) + masterSchedule.getTotalBlocks(RoomType.EXTERNAL)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protocolDialog = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelMasterScheduleStatus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lRoomsInternal = new javax.swing.JLabel();
        lRoomsExternal = new javax.swing.JLabel();
        lSeatsExternal = new javax.swing.JLabel();
        lBlocksCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        spTree = new javax.swing.JScrollPane();
        jt = new javax.swing.JTree();
        spTable = new javax.swing.JScrollPane();

        protocolDialog.setTitle("Protokoll der Strategieausführung");

        jButton2.setText("Schließen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout protocolDialogLayout = new javax.swing.GroupLayout(protocolDialog.getContentPane());
        protocolDialog.getContentPane().setLayout(protocolDialogLayout);
        protocolDialogLayout.setHorizontalGroup(
            protocolDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(protocolDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(protocolDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, protocolDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        protocolDialogLayout.setVerticalGroup(
            protocolDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, protocolDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(6, 6, 6))
        );

        jLabel1.setText("Räume (intern):");

        jLabel2.setText("Räume (extern):");

        jLabel3.setText("Externe Sitzplätze:");

        jLabel4.setText("Anzahl Termine:");

        lRoomsInternal.setText("jLabel5");

        lRoomsExternal.setText("jLabel6");

        lSeatsExternal.setText("jLabel7");

        lBlocksCount.setText("jLabel8");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Informationen zum Gesamtplan");

        javax.swing.GroupLayout panelMasterScheduleStatusLayout = new javax.swing.GroupLayout(panelMasterScheduleStatus);
        panelMasterScheduleStatus.setLayout(panelMasterScheduleStatusLayout);
        panelMasterScheduleStatusLayout.setHorizontalGroup(
            panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                        .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lRoomsExternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lRoomsInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lBlocksCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lSeatsExternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2)))
                        .addGap(497, 497, 497))))
        );
        panelMasterScheduleStatusLayout.setVerticalGroup(
            panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterScheduleStatusLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lRoomsInternal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lRoomsExternal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lSeatsExternal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMasterScheduleStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lBlocksCount))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Protokoll zeigen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(200);

        jt.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtValueChanged(evt);
            }
        });
        spTree.setViewportView(jt);

        jSplitPane1.setLeftComponent(spTree);
        jSplitPane1.setRightComponent(spTable);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtValueChanged
        final int timeSlotWidth = 25;
        
        if (jt.getLastSelectedPathComponent() == null) {
            spTable.setViewportView(lSelectNode);
            return;
        }
        
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) jt.getLastSelectedPathComponent();
        
        if (n.getUserObject() instanceof Room) {
            Schedule schedule = masterSchedule.getSchedule((Room) n.getUserObject());
            scheduleTableModel.setSchedule(schedule);
            scheduleTable.getColumnModel().getColumn(0).setPreferredWidth(timeSlotWidth);
            spTable.setViewportView(scheduleTable);
        } else if (n.getUserObject() instanceof Academic) {
            Schedule schedule = masterSchedule.getSchedule((Academic) n.getUserObject());
            scheduleTableModel.setSchedule(schedule);
            scheduleTable.getColumnModel().getColumn(0).setPreferredWidth(timeSlotWidth);
            spTable.setViewportView(scheduleTable);
        } else if (n.getUserObject() instanceof Semester) {
            Semester semester = (Semester) n.getUserObject();
            Schedule schedule = masterSchedule.getSchedule(semester.getStudyProgram(), semester);
            scheduleTableModel.setSchedule(schedule);
            scheduleTable.getColumnModel().getColumn(0).setPreferredWidth(timeSlotWidth);
            spTable.setViewportView(scheduleTable);
        } 
        else if(n.getUserObject() instanceof String && n.getUserObject().toString().equals("Gesamtplan")) {
            spTable.setViewportView(panelMasterScheduleStatus);
        }
        else {
            spTable.setViewportView(lSelectNode);
        }

    }//GEN-LAST:event_jtValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        protocolDialog.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         jTextArea1.setText(StrategyProtocol.getProtocol());
         protocolDialog.setSize(1024, 800);
         protocolDialog.setLocationRelativeTo(null);;
         protocolDialog.setVisible(true);
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jt;
    private javax.swing.JLabel lBlocksCount;
    private javax.swing.JLabel lRoomsExternal;
    private javax.swing.JLabel lRoomsInternal;
    private javax.swing.JLabel lSeatsExternal;
    private javax.swing.JPanel panelMasterScheduleStatus;
    private javax.swing.JDialog protocolDialog;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTree;
    // End of variables declaration//GEN-END:variables
}
